apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bc5a58vid-go-gitops
  description: This is GitOps manifest for bc5a58vid-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=bc5a58vid-go
    backstage.io/kubernetes-id: bc5a58vid-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bc5a58vid-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bc5a58vid-go
